# Generated by Django 5.1 on 2024-11-16 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0003_delete_courses_alter_student_courses'),
        ('teachers', '0002_alter_teacher_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('evaluation_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('evaluation_type', models.CharField(choices=[('EXAM', 'Prova'), ('ASSIGNMENT', 'Trabalho'), ('PARTICIPATION', 'Participação'), ('QUIZ', 'Quiz'), ('FINAL', 'Prova Final')], default='EXAM', max_length=15)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='courses.courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='teachers.teacher')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'course', 'evaluation_date', 'evaluation_type'), name='unique_grade_per_evaluation')],
            },
        ),
    ]
